substitutions:
  name: "bticino-covers"

esphome:
  name: $name

external_components:
  - source: components

esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE


# Enable Home Assistant API
api:
  encryption: 
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$name Fallback Hotspot"
    password: !secret captive_portal_password

captive_portal:

switch:
  - platform: gpio
    pin: 38
    name: "neopixel-enable"
    restore_mode: ALWAYS_ON
    internal: true

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: 39
    num_leds: 1
    name: "NeoPixel"

bticino_bus:

cover:
  - platform: bticino_cover
    name: "Door"
    address: 0x74
    open_duration: 59sec
    close_duration: 59sec
    tilt_duration: 1.5sec
  - platform: bticino_cover
    name: "Street"
    address: 0x75
    open_duration: 59sec
    close_duration: 59sec
    tilt_duration: 1.5sec
  - platform: bticino_cover
    name: "Terrace"
    address: 0x65
    open_duration: 59sec
    close_duration: 59sec
    tilt_duration: 1.5sec
  - platform: bticino_cover
    name: "Terrace Door"
    address: 0x64
    open_duration: 59sec
    close_duration: 59sec
    tilt_duration: 1.5sec
  - platform: bticino_cover
    name: "Bedroom"
    address: 0x76
    open_duration: 59sec
    close_duration: 59sec
    tilt_duration: 1.5sec

sensor:
  - platform: uptime
    name: "$name uptime"
    device_class: duration

  - platform: wifi_signal
    name: "$name wifi signal"
